services:
    # PostgreSQL Database
    postgres:
        image: postgres:15
        container_name: ai_komekshi_postgres
        environment:
            POSTGRES_DB: ai_komek
            POSTGRES_USER: komek_user
            POSTGRES_PASSWORD: REDACTED
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

    # Redis (for caching and sessions)
    redis:
        image: redis:7-alpine
        container_name: ai_komekshi_redis
        ports:
            - '6379:6379'
        restart: unless-stopped

    # FastAPI Backend
    backend:
        build:
            context: ./backend
            dockerfile: dockerfile
        container_name: ai_komekshi_backend
        env_file:
            - ./backend/.env.production
        ports:
            - '8000:8000'
        depends_on:
            - postgres
            - redis
        restart: unless-stopped
        volumes:
            - ./backend:/app
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000

    # Next.js Frontend
    frontend:
        build:
            context: ./front
            dockerfile: Dockerfile
        container_name: ai_komekshi_frontend
        env_file:
            - ./front/.env.production
        ports:
            - '3000:3000'
        depends_on:
            - backend
        restart: unless-stopped
        # In production, do not override the built app with a bind mount
        # volumes:
        #     - ./front:/app
        #     - /app/node_modules
        environment:
            - NODE_ENV=production
            - NEXTAUTH_URL=http://localhost:3000
            - AUTH_TRUST_HOST=true
            - NEXTAUTH_SECRET=dev-secret-change-me
            - AUTH_SECRET=dev-secret-change-me
            - NEXT_PUBLIC_API_URL=http://backend:8000/api
            - API_URL=http://backend:8000/api
        # Start Next.js on all interfaces
        command: sh -c "npm run start -- -H 0.0.0.0 -p 3000"

volumes:
    postgres_data:
